<?php

namespace A2x\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TodolistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodolistRepository extends EntityRepository
{
}
