security:
    encoders:
        A2x\BlogBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: A2xBlogBundle:User
                property: username

    firewalls:
        administrators:
            pattern: ^/
            form_login:
                check_path:  login
                login_path:  login
            logout: true
            security: true
            anonymous: true
            access_denied_url: access_denied

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
        Post:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/lists, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        

    